version: 1.2
workflows: 
  - name: "SLF-pipeline"
    subclass: "WDL"
    primaryDescriptorPath: /workflows/SLF_main_workflow.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

