version: 1.2
workflows: 
  - name: "SLF-main-pipeline"
    subclass: "WDL"
    primaryDescriptorPath: /workflows/SLF_main_workflow.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
        
  - name: "slf-compscreen"
    subclass: "WDL"
    primaryDescriptorPath: /workflows/slf_compscreen_wf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
  - name: "slf-subset"
    subclass: "WDL"
    primaryDescriptorPath: /workflows/slf_subset_wf.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/



